# Generated by Django 4.1 on 2022-08-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
    ]
